---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot: